spring.application.name=mrbyte

bot.name=test_mr_byte_bot
bot.token=${BOT_TOKEN}

spring.ai.openai.api-key=${OPENAI_API_KEY}

message.analysis.prompt=You are efficient request types determiner, who accurately identifies\
  \ users purposes. You will get an input data and your task is to define \
  to which of {messageTypes} it belongs to. \
  \
  IMPORTANT: you must bring the answer ONLY in ONE WORD, so be careful with your determination.

